Side icon Bar added
purnima143/Kurakoo pull request #213
Opened 2021-04-18 12:01 UTC by vedant-jain03

## Related Issuse

- Info about Issue or bug

Closes: #204 

#### Describe the changes you've made

I have added material ui dependency for icons and also a good side bar satisfying theme color.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.(Specially for Backend)
- [x] My changes generate no new warnings.

## Screenshots

https://user-images.githubusercontent.com/76901313/115144730-eb9fdf00-a06b-11eb-94ec-eff1edd66419.mp4

2021-04-18 14:52 UTC, vedant-jain03 commented
@codewithvk Please review

2021-04-19 04:20 UTC, codewithvk requested changes
@vedant-jain03 Please do right after read in PR Template. Your code not working.

2021-04-19 04:20 UTC, codewithvk commented on client/src/Component/homepage/homepage.js
> +            <Link to="/signup"><div className="sign-up montserrat-bold-white-24px">{signUp}</div></Link>
You need to add  /div and remove error from your code.

2021-04-19 04:20 UTC, codewithvk commented on client/src/Component/homepage/homepage.js
> +            <Link to="/signup"><div className="sign-up montserrat-bold-white-24px">{signUp}</div></Link>
![temp](https://user-images.githubusercontent.com/61119120/115180966-74faf400-a0f4-11eb-818a-bfa38481b624.png)

2021-04-19 04:28 UTC, vedant-jain03 reviewed
Updated

2021-04-19 05:22 UTC, merged

2021-04-19 05:22 UTC, codewithvk commented
@vedant-jain03 Thanks for PR :)