Backend: Image Upload Functionality
purnima143/Kurakoo pull request #253
Opened 2021-04-22 13:59 UTC by Subham142

Closes: #220 

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.(Specially for Backend)
- [ ] My changes generate no new warnings.

2021-04-22 14:00 UTC, Subham142 commented
@codewithvk  please review it
My largest contribution till now :)

2021-04-22 19:12 UTC, codewithvk requested changes

2021-04-22 19:12 UTC, codewithvk commented on client/src/Component/homepage/homepage.js
> +import React,{useState,useEffect} from "react";
Why are you create a new Homepage component? You can refer [here](https://github.com/purnima143/Kurakoo/blob/master/client/src/components/homepage/homepage.js)

2021-04-23 04:32 UTC, Subham142 commented
I really don't know why the homepage is showing here. I didn't do anything there
Should I paste the whole code from the updated repo into the homepage?

2021-04-23 06:08 UTC, codewithvk commented
> ould I paste the

This happening because you don't fetch data.So first fetch data and push them again in PR :)

2021-04-23 06:15 UTC, Subham142 commented
Like this?

2021-04-23 06:40 UTC, codewithvk commented
`npm pull `

2021-04-23 07:03 UTC, Subham142 commented
its says already up to date
![Screenshot (106)](https://user-images.githubusercontent.com/60570595/115832045-08ebf900-a430-11eb-985b-ea38ded17f9b.png)

2021-04-23 08:20 UTC, Subham142 commented
> > I really don't know why the homepage is showing here. I didn't do anything there
> > Should I paste the whole code from the updated repo into the homepage?
> 
> This happening because you don't fetch data.So first fetch data and push them again in PR :)

done

2021-04-23 17:18 UTC, codewithvk requested changes

2021-04-23 17:18 UTC, codewithvk commented on client/src/Component/homepage/homepage.js
> +import React,{useState,useEffect} from "react";
You can create a new component `client/src/components/homepage/homepage.js` this path, check `components` spelling.

2021-04-23 17:19 UTC, codewithvk commented on client/src/Component/homepage/homepage.js
> +import React,{useState,useEffect} from "react";
or if you found already component of homepage then delete it :)

2021-04-24 08:41 UTC, Subham142 commented
@codewithvk  i deleted the wrong homepage
I reverte it and deleted the Componant/homepage

2021-04-24 10:57 UTC, codewithvk commented
@Subham142 glad to merge your large contribution 🥇

2021-04-24 10:58 UTC, merged

2021-04-24 12:46 UTC, Subham142 commented
@codewithvk  i thought backend were lvl 3

2021-04-24 12:47 UTC, codewithvk commented
@Subham142 Actually i am confused with level 2 and 3!