Added dark mode in Pages accept home page
purnima143/Kurakoo pull request #270
Opened 2021-04-25 12:00 UTC by vedant-jain03

## Related Issuse

- Info about Issue or bug

Closes: #262 

#### Describe the changes you've made

Added dark mode in Pages accept home page

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.(Specially for Backend)
- [x] My changes generate no new warnings.

2021-04-25 12:01 UTC, vedant-jain03 commented
@purnima143 I have added dark mode in signup, sign in, feed, notification, add question pages as You have stated 
Please review

2021-05-01 07:30 UTC, vedant-jain03 commented
@codewithvk Can you please review and merge this PR?
Because whenever their are any changes in pages my PR is conflicting with that.?

2021-05-01 14:25 UTC, codewithvk commented
@vedant-jain03 Attach screenshot for it &
@purnima143 ^look it

2021-05-02 11:02 UTC, vedant-jain03 commented
# Singup
![bandicam 2021-05-02 16-27-09-563](https://user-images.githubusercontent.com/76901313/116810836-a0a1c380-ab63-11eb-8c66-3fae78acde98.jpg)
# Sign In
![bandicam 2021-05-02 16-27-28-889](https://user-images.githubusercontent.com/76901313/116810838-a1d2f080-ab63-11eb-86dd-6f7823aeb1d2.jpg)
# Feed
![bandicam 2021-05-02 16-28-00-876](https://user-images.githubusercontent.com/76901313/116810841-a39cb400-ab63-11eb-8d0d-541f2b3458c5.jpg)
# Notification
![bandicam 2021-05-02 16-28-25-257](https://user-images.githubusercontent.com/76901313/116810844-a5667780-ab63-11eb-8e8b-35e6fff91ff4.jpg)
# Add a Question
![bandicam 2021-05-02 16-28-42-182](https://user-images.githubusercontent.com/76901313/116810847-a697a480-ab63-11eb-9e78-d5e17d5d2e64.jpg)

These are the pages where I changed dark mode and it is not conflicting with any files.
If you are satisfy Kindly review and Merge

2021-05-02 11:07 UTC, codewithvk requested changes
@vedant-jain03 Hey rather than changing all components of dark mode, Can we think about a generalized CSS Variable which can be maintained by the mode?

2021-05-03 10:43 UTC, vedant-jain03 commented
> @vedant-jain03 Hey rather than changing all components of dark mode, Can we think about a generalized CSS Variable which can be maintained by the mode?

Actually I even tried that but the thing is that Every component have different CSS styles so it will be very lengthy to give dark mode to every variable. For smooth rendering I used invert color.
Because toggling so many dark classes at time may lead to stack overflow.

2021-05-03 12:24 UTC, codewithvk commented
> > @vedant-jain03 Hey rather than changing all components of dark mode, Can we think about a generalized CSS Variable which can be maintained by the mode?
> 
> Actually I even tried that but the thing is that Every component have different CSS styles so it will be very lengthy to give dark mode to every variable. For smooth rendering I used invert color.
> Because toggling so many dark classes at time may lead to stack overflow.

Ya Agree with this, Let merge as of now, When the entire application has been ready then we will customize CSS.
Btw thanks for contributing

2021-05-03 12:24 UTC, codewithvk approved these changes

2021-05-03 12:25 UTC, merged