Added Team Section
purnima143/Kurakoo pull request #293
Opened 2021-05-01 14:07 UTC by vedant-jain03

## Related Issuse

- Info about Issue or bug

Closes: #279 

#### Describe the changes you've made

I have used Github API of this repo and using Use effect I have fetch the data of Contributors and Mentors.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.(Specially for Backend)
- [x] My changes generate no new warnings.

2021-05-01 14:08 UTC, vedant-jain03 commented
@codewithvk I have added Team Section In about us Please review.
I am sure it will satisfy you.

2021-05-01 14:21 UTC, codewithvk commented
@vedant-jain03 Can you attach a screenshot, please!

2021-05-01 14:23 UTC, codewithvk requested changes

2021-05-01 14:23 UTC, codewithvk commented on client/src/components/Team/team.jsx
> +            console.log(data);
Here mentor name also repeated so remove the mentors and project admin name from the contributor.

2021-05-01 14:23 UTC, codewithvk commented on client/src/components/Team/team.jsx
> +              data.filter(element => !(element.login === "smaranjitghose" || element.login === "anushbhatia"))
I am not getting this line, Can you elaborate more?

2021-05-01 14:28 UTC, vedant-jain03 reviewed
Filtered

2021-05-01 14:29 UTC, vedant-jain03 commented
@codewithvk I have used 
data.filter function so that mentors and owner id should not show again.

2021-05-02 02:04 UTC, vedant-jain03 commented
https://user-images.githubusercontent.com/76901313/116799750-b6d66200-ab18-11eb-9280-0486231982c8.mp4

Have a look at this. @codewithvk

2021-05-02 03:16 UTC, merged