restricts user
purnima143/Kurakoo pull request #309
Opened 2021-05-08 15:59 UTC by himanshujaidka

## Related Issuse

- Info about Issue or bug

Closes: #308 [issue number that will be closed through this PR]
@codewithvk pls help

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.(Specially for Backend)
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

2021-05-09 04:24 UTC, codewithvk requested changes
Can you please tell me where is middleware condition?

2021-05-10 18:31 UTC, codewithvk commented on server/src/common-middleware/middleware.js
> +    if(req.user.role == "user"){
why are you check this one?

2021-05-12 10:18 UTC, himanshujaidka commented
@codewithvk any updates

2021-05-13 15:51 UTC, codewithvk commented
@himanshujaidka This might be not working as we think, Do you have any other approach!?

2021-05-13 15:53 UTC, himanshujaidka commented
@codewithvk will let you know

2021-05-17 18:29 UTC, himanshujaidka commented
@codewithvk tell me that how should I will able to increase the counter to plus one automatically after the creation of space. That when the user will create space, then in its respected database, the counter should increase to 1. And for this first, we should declare counter inside spaces models file and then after the creation of space, it would be increased to 1. Did you get what I am able to deliver?

2021-05-21 20:13 UTC, closed without merging