fixed issue #66
purnima143/Kurakoo pull request #68
Opened 2021-03-13 13:48 UTC by Subham142

## Related Issuse

Warnings on the console

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made

added alt to the img tag and diabled the enlint

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

![Screenshot (36)](https://user-images.githubusercontent.com/60570595/111032132-cc8cac80-8430-11eb-90a7-8bf933d6f8f7.png)

2021-03-13 14:02 UTC, codewithvk requested changes

2021-03-13 14:02 UTC, codewithvk commented on client/src/Component/SignIn/SignIn.js
> +                    <img className="signin_image" src="./images/Formimage.png" alt=""></img>
Please add to text in alt
ex. < ... alt="signin_image">
You should do for all.

2021-03-13 14:57 UTC, codewithvk commented
@purnima143 could you merge it!

2021-03-13 15:05 UTC, merged

2021-03-14 04:13 UTC, purnima143 commented
@all-contributors please add @Subham142  for bug